### ISSUE TITLE
Make our kernel compilers (rasta and dartk) use correct sdk and correct package root

### ISSUE THREAD

**Issue by mkustermann** [dart-archive/kernel_sdk#17]
We need to ensure both, rasta and dartk, are using
- the package-root `./tools/test.py` is supplying
- the dart-sdk `./tools/test.py` is supplying (including using it for the patch files)

/cc @peter-ahe-google @asgerf

**Comment by asgerf** [comment]
Patch for dartk:
https://chromereviews.googleplex.com/484977013/

**Comment by mkustermann** [comment]
We should also think about whether it would be possible to use `checkout/sdk/sdk/lib` instead of `checkout/sdk/out/<build-dir>/dart-sdk/lib` because building the `create_sdk` make target takes a long time (in particular in debug mode), since it involes building analyzer summaries ....

**Comment by asgerf** [comment]
What exactly is the difference between the two SDKs?

**Comment by mkustermann** [comment]
We are generating a patched sdk which has everything we need.
