### ISSUE TITLE
Switch to Analyzer as our primary front-end

### ISSUE THREAD

**Issue by mraleph** [dart-archive/kernel_sdk#20]
- [x] Cherry pick the switch to dart2js syntax for VM
- [x] Support parsing patch files in dartk 
- [x] Support `super.` calls in mixins
- [x] Support dependency discovery to be able to find flutter.

**Comment by mkustermann** [comment]
The patch file syntax support was handled by a34913a99b587e385536b463ec82e9bc529ddeec (as a side effect) due to merging with `dart-lang/sdk@master` which added support for it.

**Comment by mkustermann** [comment]
We switched and rasta is gone!
