### ISSUE TITLE
Try indexes are not correct for inlined finally code

### ISSUE THREAD

**Issue by kmillikin** [dart-archive/kernel_sdk#25]
@mkustermann @mraleph When finally blocks are translated at the point of a break or return, the code in the finally block needs to be in a flow-graph block with the correct try index, in case it throws.

```dart
main() {
  try {
    try {
      return;
    } finally {
      print('inner');
      throw 0;
    }
  } finally {
    print('outer');
  }
}
```

should print "inner" and "outer", but prints "inner", "inner", and "outer".

**Comment by mkustermann** [comment]
I think https://codereview.chromium.org/2487183002/ should fix it.

**Comment by mkustermann** [comment]
The CL which should hopefully fix this issue landed on the main sdk.
