### ISSUE TITLE
Test async transformer using CO19 tests

### ISSUE THREAD

**Issue by mraleph** [dart-archive/kernel_sdk#3]

**Comment by mkustermann** [comment]
29be7c4b1955169b37c13316a64999b981f37f1c added functionality to `./tools/test.py` to use run ir2ir transformers before running the resulting Kernel IR file with the VM.

Our continuations branch has been updated in 61088635d48ac5337b5dae3b2ca659317f58a226 to reflect which async/await tests are passing now with our transformer (and which tests are still failing).
