### ISSUE TITLE
Make rasta frontend correctly report compile-time errors

### ISSUE THREAD

**Issue by mkustermann** [dart-archive/kernel_sdk#4]
Running co19 tests with rasta produces a very high number of `MissingCompileTimeError`s (out of 8051 tests 440 are failing due compile-time errors not being correctly reported):

```
kernel_sdk $ ./tools/build.py -mdebug -ax64 runtime
kernel_sdk $ ./tools/test.py -mdebug -ax64 -crasta co19
```

/cc @peter-ahe-google

**Comment by peter-ahe-google** [comment]
Fix on the way in [https://github.com/dart-lang/rasta/issues/78].
